import { NextPage } from 'next';
import { Stack, Text } from '@chakra-ui/react';

const TermsOfUse: NextPage = () => {
    return (
        <Stack className='container' my='32' rowGap='5'>
            <Text fontWeight='bold' fontSize='lg'>Terms and Conditions for EducationDirectory.org</Text>
            <Text>Revised September 3, 2020</Text>
            <Text>PLEASE CHECK THIS PAGE FREQUENTLY FOR UPDATES. THE CURRENT VERSION OF THESE TERMS AND CONDITIONS APPLY EACH TIME YOU USE THE SITE. PLEASE READ THIS DOCUMENT CAREFULLY. IT CONTAINS VERY IMPORTANT INFORMATION ABOUT YOUR RIGHTS AND OBLIGATIONS, AS WELL AS LIMITATIONS AND EXCLUSIONS THAT MAY APPLY TO YOU. THIS DOCUMENT CONTAINS A DISPUTE RESOLUTION CLAUSE.</Text>
            <Text>This Agreement ("Agreement"), is made by and between Education Directory ("We," "Us," or "Our"), with mailing address of 3219 E Camelback Rd. Ste 221, Phoenix, AZ 85018, pursuant to its provision of the Web Site called EducationDirectory.org ("Web Site"), and you ("You," "Your" or "Yourself"). The Web Site, all products or services offered on this site, all text, pictures, graphics, logos, button items, images, works of authorship and other information and all revisions, modifications, and enhancements thereto ("Content") are subject to the following terms and conditions, which may be updated from time to time.</Text>
            <Text>UPON ACCESSING EDUCATIONDIRECTORY.ORG, YOU AGREE TO THESE TERMS AND CONDITIONS. PLEASE READ THESE TERMS CAREFULLY. IF YOU DO NOT AGREE WITH ANY OF THESE TERMS OR CONDITIONS, OR IF ANY OR ALL OF THE FOLLOWING ARE PROHIBITED WITHIN YOUR JURISDICTION, DO NOT ACCESS OR OTHERWISE USE THIS WEB SITE, THE PRODUCTS, OR ANY INFORMATION CONTAINED ON THIS WEB SITE. YOUR ACCESS TO AND USE OF THIS WEB SITE CONSTITUTE YOUR AGREEMENT TO ABIDE BY, AND UNDERSTANDING OF EACH OF THE TERMS AND CONDITIONS SET FORTH BELOW. IF YOU HAVE ANY QUESTIONS, VISIT THE "CONTACT US" SECTION OF OUR WEB SITE TO SUBMIT QUESTIONS TO OUR CUSTOMER SERVICE REPRESENTATIVES.</Text>
            
            <Text fontWeight='bold' fontSize='lg'>1.MANDATORY ARBITRATION.</Text>
            <Text>You understand and agree that all claims, disputes, or controversies between You and Education Directory and its parents, subsidiaries or related companies, including but not limited to tort and contract claims, claims based upon any federal, state, or local statute, law, order, ordinance, or regulation, and the issue of arbitrability, shall be resolved by final and binding arbitration using the American Arbitration Association's (AAA) Commercial Arbitration Rules (AAA Rules) in effect on the date of initiation of the arbitration, except as to those AAA Rules that conflict with or differ from this Agreement, by one or more arbitrators appointed in accordance with the said rules at a location determined by the arbitrator(s). The arbitrator shall be a lawyer with more than ten years experience or a retired or former judge. The arbitrator shall be independent of and unrelated to You. Notwithstanding any language in these Terms and Conditions to the contrary, no arbitration may be administered without the consent of all parties to the arbitration. Any controversy concerning whether a dispute is arbitrable shall be determined by the arbitrator(s) and not by the court. Judgment upon any award rendered by the arbitrator(s) may be entered by any state or federal court having jurisdiction thereof. This arbitration contract is made pursuant to a transaction in interstate commerce and its interpretation, application, enforcement, and proceedings thereunder shall be governed by the Federal Arbitration Act, 9 U.S.C. Sec. 1-16 ("FFA"). NEITHER YOU NOR WE SHALL BE ENTITLED TO JOIN OR CONSOLIDATE CLAIMS IN ARBITRATION BY OR AGAINST OTHER CONSUMERS OR ARBITRATE ANY CLAIM AS A REPRESENTATIVE OR MEMBER OF A CLASS OR IN A PRIVATE ATTORNEY GENERAL CAPACITY. The parties voluntarily and knowingly waive any right they have to a jury trial.</Text>
            
            <Text fontWeight='bold' fontSize='lg'>2.ACCURATE INFORMATION.</Text>
            <Text>In consideration of Your use of the Web Site, You agree to provide true, accurate, and current information about Yourself if prompted on Our Web Site, and agree to promptly update such information should it change or should additional information be required by Education Directory or applicable law. We reserve the right to request verification of, and You agree to be subject to verification of, any of the information provided by You for enrollment with and continued use of the Membership.</Text>
            
            <Text fontWeight='bold' fontSize='lg'>3.COMPANY NEWSLETTER AND OTHER EMAILS.</Text>
            <Text>By signing up on the Web Site, You are opting-in to receive Our newsletters by email, other special offer emails, and/or third-party emails. If You do not wish to receive these emails, You may opt-out at any time, by following the directions in the newsletter/email.</Text>
            
            <Text fontWeight='bold' fontSize='lg'>4.REQUIREMENTS. You must meet the basic requirements listed below to utilize Our Web Site.</Text>
            <Text>4.1 Age. By registering on this Web Site, You certify that You are eighteen (18) years of age or older. 4.2 Approved Locations. The Web Site is currently applicable only to those in the United States of America. You must be physically located within the United States of America while using the Web Site. 4.3 Cookies. Members must have cookies enabled. Members must access Our Partners' sites (where applications may be completed or information provided) through the Web Site. These conditions are mandatory so that the educational institution will know that You used Our Web Site to reach their respective site. 4.4 Etiquette. You shall not tamper, hack, spoof, copy, modify, or otherwise corrupt the administration, security, or proper function of any part of Education Directory’s Web Site. You shall not use robots, scripts, spiders, or crawlers or similar devices with the Education Directory Web Site. 4.5 Your Relationship To Education Directory. Your relationship to Education Directoryis one of an independent contractor and/or customer. No employee-employer relationship is created by Your use of the Web Site. 4.6 Your Relationship With Partners. We do not warranty, guarantee, or insure the quality of any product or service offered by any of the Partners. Your relationship with Partners for whom We deliver goods or services on Our Web Site, including payment for and delivery of related goods or services, and any other terms, conditions, warranties or representations associated with such dealings, are solely between You and such Partner. You agree not to hold Education Directory liable for any loss or damage of any sort incurred as the result of any such dealings or as the result of the content provided by such Partners through the Web Site. When You leave the Education Directory Web Site, You should review the terms and conditions and privacy policy applicable to that web site. 4.7 Inaccuracies/Typos. Education Directory is not responsible for typos or misprints contained within Our Web Site. We reserve the right to correct typos, errors and descriptions as needed to maintain accurate information. Under no circumstances will Education Directory be liable for misquoted content. All information and prices should be verified prior to final transactions.</Text>
            
            <Text fontWeight='bold' fontSize='lg'>5.INTELLECTUAL PROPERTY.</Text>
            <Text>You acknowledge and agree that (a) all text, pictures, graphics, logos, button items, images, works of authorship and other information and all revisions, modifications, and enhancements thereto ("Content") is the copyrighted work of Education Directory or its third party content suppliers and is protected by copyright laws, (b) the domain www.EducationDirectory.org, the Education Directory logo, all page headers, custom graphics and button icons are service marks, trademarks and/or trade dress of Education Directory (collectively, "Marks"), and (c) all other trademarks, product names, company names or logos on the Web Site are the property of their respective owners. In addition to agreeing to comply with all applicable laws, You agree You will not use any such Content or Marks from this Web Site for any purpose without the appropriate prior written authorization.</Text>
            
            <Text fontWeight='bold' fontSize='lg'>6.TERMINATION AND CANCELLATION.</Text>
            <Text>6.1 Termination. Education Directory, at Our sole discretion, may terminate your usage of the Web Site without prior notice for any reason or no reason at all, including without limitation, for (a) any violation of any provision of this Agreement; (b) aiding in or promoting circumvention of the Web Site; (c) acting against Our business interests or reputation; or (d) otherwise acting unlawfully in relationship to Education Directory or the Web Site. 6.2 End of Web Site. We may cease offering the Web Site at any time and for any reason, in Our sole discretion.</Text>
            
            <Text fontWeight='bold' fontSize='lg'>7.WARRANTIES.</Text>
            <Text>YOU EXPRESSLY AGREE THAT USE OF THE WEB SITE IS AT YOUR SOLE RISK. THE WEB SITE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. TO THE MAXIMUM EXTENT ALLOWED BY APPLICABLE LAW, WE EXPRESSLY DISCLAIM ALL WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED BY LAW, CUSTOM OR OTHERWISE, INCLUDING WITHOUT LIMITATION ANY WARRANTY OF MERCHANTABILITY, SATISFACTORY QUALITY, FITNESS FOR A PARTICULAR PURPOSE OR NON-INFRINGEMENT. WE MAKE NO WARRANTY REGARDING ANY GOODS OR SERVICES PURCHASED OR OBTAINED THROUGH THE WEB SITE OR ANY TRANSACTIONS ENTERED INTO THROUGH THE WEB SITE.</Text>
            
            <Text fontWeight='bold' fontSize='lg'>8.LIMITATION OF LIABILITY.</Text>
            <Text>TO THE FULLEST EXTENT PERMITTED BY LAW, YOU UNDERSTAND AND AGREE THAT EDUCATION DIRECTORY, INCLUDING EDUCATION DIRECTORY’S PARTNERS, OFFICERS, DIRECTORS, AGENTS, EMPLOYEES, SUBSIDIARIES, AFFILIATES, PARENTS, SUCCESSORS, AND THEIR SUPPLIERS WILL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES (INCLUDING WITHOUT LIMITATION REASONABLE ATTORNEYS FEES, EXPENSES, AND COURT COSTS) RESULTING FROM YOUR BREACH OF THIS AGREEMENT, YOUR OMISSIONS, YOUR FAILURE TO ABIDE BY ALL APPLICABLE LAWS, RULES, OR REGULATIONS, OR IN ANY WAY CONNECTED TO YOUR ACCESS TO, USE OF, OR INABILITY TO USE THE WEB SITE, PRODUCTS, ACCOUNT, MEMBERSHIP BENEFITS, CONTENT OR SOFTWARE, OR FROM YOUR ACCESS TO, USE OF, INABILITY TO USE, OR RELIANCE UPON ANY LINKED WEB SITE, EVEN IF EDUCATION DIRECTORY, OR ITS SUPPLIERS HAVE BEEN ADVISED OF THE POSSIBILITY OF THOSE DAMAGES. SOME JURISDICTIONS EITHER DO NOT ALLOW OR PLACE RESTRICTIONS UPON THE EXCLUSION OR LIMITATION OF DAMAGES IN CERTAIN TYPES OF AGREEMENTS; FOR THESE JURISDICTIONS, THE AFOREMENTIONED LIMITATION ON LIABILITY SHALL BE TO THE MAXIMUM DEGREE PERMITTED BY APPLICABLE LAW. IF, NOTWITHSTANDING THE ABOVE, LIABILITY IS IMPOSED UPON EDUCATION DIRECTORY, THEN YOU AGREE THAT EDUCATION DIRECTORY’S TOTAL LIABILITY FOR ANY OR ALL YOUR LOSSES OR INJURIES FROM EDUCATION DIRECTORY’S ACTS OR OMISSIONS, REGARDLESS OF THE NATURE OF THE LEGAL OR EQUITABLE CLAIMS ALLEGEDLY VIOLATED, SHALL NOT EXCEED $300.</Text>
            
            <Text fontWeight='bold' fontSize='lg'>9.GOVERNING LAW AND OTHER TERMS.</Text>
            <Text>9.1 Arizona Law and Jurisdiction. Any action related to this Agreement will be governed by the laws of the State of Arizona, without regard to conflict of laws Rules. Any action relating to this Agreement as permitted following the Mandatory Arbitration described above shall be brought in the state or federal courts located in the District of Arizona, and You hereby submit to the exclusive jurisdiction and venue thereof. You agree to comply with the laws of the State of Arizona and the United States of America that apply to the use of the Web Site and the compensation You may receive. If the law of Your residence prohibits or limits Your participation in the Web Site, then You are responsible for complying with such laws and You agree to indemnify Us against any breach or violation. 9.2 Enforceability; No Assignment. If any part of this Agreement is held to be unenforceable, the unenforceable part shall be given effect to the greatest extent possible and the remainder will remain in full force and effect. This Agreement is personal to You and You may not transfer, delegate, or assign this Agreement, Your Membership or other benefits You may receive as a Member to anyone. Any attempt by You to assign or delegate this Agreement shall be null and void. We may assign this Agreement at Our sole discretion. 9.3 Other Documents. This Agreement may NOT be altered, supplemented, or amended by the use of any other document(s) unless otherwise agreed to in a written agreement signed by both Education Directory and You.</Text>
            
            <Text fontWeight='bold' fontSize='lg'>10.SECURITY.</Text>
            <Text>10.1 Standard Procedures. To prevent unauthorized access, maintain data accuracy, and ensure the correct use of information, We have used appropriate industry standard procedures to protect the confidentiality of Your personal information, such as firewall, encryption, application proxies, monitoring technology, and adaptive analysis of network traffic to track abuse of Our network and its data. However, no data transmitted over the Internet can be completely secure. As a result, while We strive to protect Your personal information, We cannot guarantee the security of any information that You transmit to Us or from Our Partners and You do so at Your own risk. 10.2 No Tampering. You agree not to tamper with the proper functioning and tracking of the Web Site. Emulating or "faking" search usage and Web Site visits will lead to termination of Your account and may lead to legal action. 10.3 Unauthorized Use. ANY UNAUTHORIZED USE OR ENTRY INTO A EDUCATION DIRECTORY WEB SITE IS PUNISHABLE BY LAW, AND WILL BE PROSECUTED TO THE FULL EXTENT OF THAT LAW.</Text>
            
            <Text fontWeight='bold' fontSize='lg'>11.ENTIRE AGREEMENT.</Text>
            <Text>This Agreement, the Privacy Policy, and other terms, conditions and policies Education Directory may post on this Web Site constitute the entire Agreement between You and Us and supersede all prior agreements between the parties regarding the subject matter contained herein. This Agreement, the Privacy Policy, and other terms, conditions and policies Education Directory may post on this Web Site shall be read to be mutually consistent wherever possible. In the event of any conflict, this Agreement and the Privacy Policy will control over the Web Site. No failure of either party to exercise or enforce any of its rights under this Agreement will act as a waiver of such rights.</Text>
            
            <Text fontWeight='bold' fontSize='xl'>CONTACTING US. If You have questions about any offer, Partner, completion, Web Site or this Agreement, please email : info@educationdirectory.org.</Text>
        </Stack>
    );
};

export default TermsOfUse;