import { NextPage } from 'next';
import { Stack, Text } from '@chakra-ui/react';

const PrivacyPolicy: NextPage = () => {
    return (
        <Stack className='container' my='32' rowGap='5'>
            <Text fontWeight='bold' fontSize='lg'>Privacy Policy</Text>
            <Text>Last updated 12/2/20</Text>
            <Text>EducationDirectory.org (the “Site”) is an Internet property of Candid Maven ("Company," "we," "our" or "us"). This Privacy Policy describes how we treat personal information received about you when you visit our Site such as the collection and use of the personal information you provide. It also describes the choices available to you regarding the use of, your access to, and how to update and correct your personal information.</Text>
            <Text>This Privacy Policy applies to all Candid Maven and all other websites and applications that link to this Privacy Policy (“Services”). Please read this Privacy Policy carefully, because by visiting or using this Site as you agree to its terms.</Text>

            <Text fontWeight='bold' fontSize='lg'>Information Collected</Text>
            <Text>Personal Information: Depending on the Services you are visiting or using, we may collect various times of information from and about you, including information that can personally identify you. This information includes, but is not limited to: name, age, postal address, email address, telephone number, short message service or text message address, other wireless device address, instant messaging address, demographic information, education and scholastic information (including but not limited to level of education, desired level of educational program, and areas of interest), current occupation, military status, information about any transaction you conduct or submit to on or through the Services, and other information that would allow online or offline contact with you as an individual (collectively, “Personal Information”).</Text>
            <Text>Non-Personal Information: We also collect Usage Information (as defined below) and other information from and about you that does not personally identify you or allow us or others to contact you individually online or offline ("Non-Personally Identifiable Information" or "Non-PII"). We may combine Non-PII with other information in a way that allows you to be identified or personally contacted. If this happens, we will treat the combined information as Personal Information.</Text>
            
            <Text fontWeight='bold' fontSize='lg'>How We Collect Information: We may collect information from you in the following ways:</Text>
            <Text>Information Provided by You. We collect information provided by you when you (1) inquire about or obtain our services or products; (2) communicate with us or request information about or from us, whether via email or other means; (3) fill out forms or fields on the Services; (4) register as a user or sign-up for any of our newsletters, materials or services through the Services; (5) enter into online transactions; (6) create profiles; (7) provide college reviews or participate in our online surveys or questionnaires; (8) input information into our interactive programming features or participate in our online forums; (9) participate in any of our marketing initiatives, including contests, scholarship offers, events, or promotions; and (10) post to the Services or provide user-generated content or submissions to us, including without limitation media files, photos, videos, documents or other information, and contributions to a chat room, list serve, blog, or other open forum or community feature that we make available on the Services ("User Contributions").</Text>
            <Text>Information from Other Sources. We may collect information about you from other services that we may provide, our affiliates, third-party or public sources (such as from public forums, social networks, and blogs), other users of the Services, and our business partners.</Text>
            <Text>Automatic Information Collection. We and our service providers use automatic data collection technologies to collect and store Usage Information (as defined below). This information helps us evaluate how our visitors use and navigate the Site on an aggregate basis, including but not limited to the number and frequency of visitors to each Site, and the length of their visits. We may combine this automatically collected log information with other information we collect about you. We do this to improve services we offer you, to improve marketing, analytics, or site functionality. We also may allow third-party advertising companies and ad networks to use automatic data collection technologies to collect Usage Information for purposes of providing interest based ads. See the Automatic Information Collected Technologies and Usage Information and the Third-Party Advertisers and Interest-Based Ads sections for more information.</Text>
            
            <Text fontWeight='bold' fontSize='lg'>How We Use the Information Collected</Text>
            <Text>We may use your information, including Personal Information, to:</Text>
            <Text>Provide products and services requested by you;</Text>
            <Text>Provide customer support, including responding to your requests and questions and troubleshooting and resolving problems or complaints, and for any other purposes that we deem appropriate;</Text>
            <Text>Verify the information you provide to us;</Text>
            <Text>Communicate with you;</Text>
            <Text>Confirm your identity and eligibility to use the Services;</Text>
            <Text>Establish and manage your account, as applicable;</Text>
            <Text>Perform research and analysis to develop and improve the Services and other products and services that we may offer;</Text>
            <Text>Understand and anticipate your use of or interest in, our products, services, and content, and the products, services, and content offered by others;</Text>
            <Text>Develop and display products, services, and content tailored to your interests on the Services and other online properties;</Text>
            <Text>Measure the overall effectiveness of our online advertising, content, and programming, and other activities;</Text>
            <Text>Offer you personalized information and products, services, promotions, contests, or scholarships of ours, our affiliates, or our third-party business partners that may be of interest to you;</Text>
            <Text>Manage our business and operations;</Text>
            <Text>We use the information we automatically collect (such as contact information, IP address and basic browser and system details) to help us optimize our sites and the services we offer on the Sites and may offer in the future;</Text>
            <Text>To provide you with a customized browsing experience;</Text>
            <Text>Protect the security and integrity of the Services;</Text>
            <Text>Carry out our obligations and enforce our rights arising from this Privacy Policy, the Terms of Use and any other applicable agreements and policies;</Text>
            <Text>Use or post User Contributions as permitted in our Terms of Use; and</Text>
            <Text>Fulfill any other purposes for which you provide your information and for any other purpose as described to you at the time your information is collected or for which your consent is given.</Text>
            
            <Text fontWeight='bold' fontSize='lg'>How We May Share Your Information</Text>
            <Text>We may disclose or share information from or about you, including your Personal Information, as follows:</Text>
            <Text>With Candid Maven’s affiliated companies for support of our internal and business operations, for cross-marketing purposes or in connection with a request made by you or your opt-in or consent.</Text>
            <Text>With our non-affiliated third-party business partners, service providers, and vendors to enable them to assist us in providing you the products or services you request through the Services or to provide us with support for our internal and business operations, such as customer service, data processing, data storage, research, analytics, web hosting, marketing, providing suggestions and strategies to improve our business processes and the services we provide, and delivery of promotional or transactional materials. We may provide your personal information to companies that provide services to help us with our business activities such as offering customer service. These companies are authorized to use your Personal Information only as necessary to provide these services to us. With other non-affiliated companies, parties, or organizations (with whom we maintain business relationships) when you engage in certain activities through the Services or services that are sponsored or provided by them, including, but not limited to requesting or purchasing products or services offered by these third parties, electing to receive information or communications from them, or electing to participate in contests, sweepstakes, games, scholarships, or other programs sponsored or provided by these third parties, in whole or in part.</Text>
            <Text>If you submit information to an advertiser or other third party that is made available on or through Candid Maven, the information obtained during your visit to that advertiser’s website, and the information you give to the advertiser will be governed by the advertiser’s privacy policy. For further information on such advertiser’s use of your information, please visit the applicable privacy policy of such advertisers. Advertisers made available on this site have separate policy practices for which Candid Maven has no responsibility or liability.</Text>
            <Text>In addition, from time to time, we may share Personal Information (such as e-mail addresses and other contact information such as name, email address and phone number) with selected third parties, so they may offer educational or non-educational goods and services that we believe may be of interest to our customers. To opt-out of our sharing of your information with such third parties, see the Your Choices about How We Use and Disclose Your Information section.</Text>
            <Text>With any person who, in our reasonable judgment, is authorized to receive your information, such as your agent, attorney, parent, legal guardian, or co-signor of a loan application.</Text>
            <Text>We may disclose information we collect from or about you when we believe disclosure is appropriate to comply with the law; when we believe that disclosure is necessary to comply with a judicial proceeding, court order or other similar legal process served on our Site; to enforce or apply applicable terms and conditions and other agreements; or to protect the rights, property, or safety of our company, our affiliates, our other customers or users of the Services, or others. If some or all of our business assets are sold or transferred, whether through a sale, acquisition, merger, consolidation, reorganization, bankruptcy, or other corporate change involving us and/or our affiliates, we may transfer the corresponding information regarding our customers and users of the Services, including Personal Information, to third parties evaluating or facilitating the transaction. We also may retain a copy of such information. Nothing in this Privacy Policy is intended to interfere with our ability to transfer all or part of our business, equity interests, or assets (including the Services) to an affiliate or non-affiliated third party at any time, for any purpose, without any limitation, and without notice or any compensation to you, whatsoever.</Text>
            <Text>We cannot ensure that all of your private communications and other Personal Information will never be disclosed in ways not otherwise described in this Policy. For example, we may be forced to disclose information to the government or third parties under certain circumstances, third parties may unlawfully intercept or access transmissions or private communications, or users may abuse or misuse your personal information that they unlawfully collect from the Site. We will try to protect your privacy, however, we do not promise, and you should not expect, that your Personal Information or private communications will always remain private.</Text>
            
            <Text fontWeight='bold' fontSize='lg'>Information Collection and Usage</Text>
            <Text>We and our service providers automatically collect "Usage Information" from or about you, such as information about your computer or mobile device, IP address, web browser, computer or device platform, related software and settings you are using, browsing actions and patterns, the referring page that linked you to us and the website you visit after using the Services, and other usage activity on the Services. Collection of Usage Information helps us to improve the Services and to deliver a better and more personalized service by enabling us to, among other things: (1) estimate our audience size and usage patterns; (2) store information about your preferences, allowing us to customize the Services according to your individual interests; (3) speed up your searches; and (4) recognize you when you return to the Services.</Text>
            <Text>We and certain third parties, such as but not limited to advertising service providers, may use certain technologies to collect information about your online activities over time and across different services.</Text>
            <Text>The automatic collection technologies we and our service providers may use for this automatic information collection include:</Text>
            <Text>Cookies (or browser cookies). A cookie is a small data file that is sent to your browser or related software and stored on your computer's hard drive when you visit a website. Generally, cookies can track what you look at and where you travel on websites and what transactions you make. They can also store Personal Information about you, including your username and password. A "session cookie" expires immediately when you end your browsing session with the particular website. A "persistent cookie" stores information on your hard drive so when you end your browsing session and return to the same website later, the cookie information is still available. The Services may use both types of cookies.</Text>
            <Text>Flash Cookies. Certain features of the Services may use locally stored objects (or Flash cookies) to collect and store information about your preferences and navigation to, from and on the Services.</Text>
            <Text>Pixels. Pages of the Services and any emails we send to you may contain small electronic files known as pixels that permit us, for example, to count users who have visited those pages or opened our emails and for other related website analytics (e.g., recording the popularity of certain website content and verifying system and server integrity).</Text>
            <Text>We may receive reports based on the use of these technologies by these companies on an individual as well as aggregated basis.</Text>
            
            <Text fontWeight='bold' fontSize='lg'>How We Secure Your Information</Text>
            <Text>The site maintains physical, electronic and managerial practices and procedures designed to ensure the security, integrity and confidentiality of customer information. We limit and restrict access to customer information only to those employees who need it to carry out their business functions. We also educate our employees about safeguarding customer information and preventing its unauthorized access, disclosure or use. The site’s employees with access to personal information are also bound to adhere to this policy. The site will monitor and adopt, as appropriate, new technological improvements that are designed to aid in ensuring the accuracy and security of customer information.</Text>
            <Text>Customers utilizing our service are provided access numbers, account numbers and passwords to access their account information on-line. E-mails sent to subscribers are not encrypted and have the same level of protection as general emails.</Text>
            
            <Text fontWeight='bold' fontSize='lg'>Data Verification</Text>
            <Text>If applicable to the Services you are using, we work with service providers to verify your address and phone number, in order to accurately match you to a course of study and school program, if applicable.</Text>
            
            <Text fontWeight='bold' fontSize='lg'>Third-Party Advertisers</Text>
            <Text>With the exception of certain of our webpages, services or features that may collect sensitive Personal Information such as financial information, we may permit third-party advertising companies or ad networks to display third-party advertisements on our websites and/or automatically collect Usage Information from our websites for purposes of determining your preferences and delivering interest-based advertising and content to you on the Services or other online properties, including those operated by third parties. Those ads may include ads for our products or services or for other companies' products or services.</Text>
            <Text>These third-party advertisers may combine the Usage Information with Personal Information you directly submit to them or that they receive from other sources, or the Usage Information they collect may include information that could allow someone to specifically contact you online without necessarily knowing your identity. We do not have access to or control over the automatic collection technologies that these third-party advertisers may use, and the information practices of these third-party advertisers are subject to these parties' respective privacy policies, not this Privacy Policy.</Text>
            <Text>If you click on a link to a third party site, including on an advertisement, you will leave the Site you are visiting and go to the site you selected. Because we cannot control the activities of third parties, we cannot accept responsibility for any use of your personally identifiable information by such third parties, and we cannot guarantee that they will adhere to the same privacy practices as this Site. We encourage you to review the privacy statements of any other service provider from whom you request services. If you visit a third party website that is linked to this Site, you should read that site’s privacy statement before providing any personally identifiable information.</Text>
            
            <Text fontWeight='bold' fontSize='lg'>Third-Party Content</Text>
            <Text>The Services and all electronic communications sent in connection with the Services, may contain links, videos, images, or other content provided by third parties. We do not necessarily endorse these websites, products, services, or practices. We do not control, and are not responsible for, the privacy and security practices of these third parties. We recommend that you review the privacy and security policies of these third parties to determine how they handle information they may collect from or about you once you are on the third party site.</Text>
            <Text>The Services may also allow you to engage with social media features, such as the Facebook Like button, Google Plus, and Twitter widgets, when you are logged into those services. These features may collect information about your IP address and which page you are visiting on the Services, and they may set a cookie to make sure the feature functions properly. Your interactions with these features and the information from or about you collected by them are governed by the privacy policies of the companies that provide them.</Text>
            
            <Text fontWeight='bold' fontSize='lg'>Your Rights and Choices</Text>
            <Text>We strive to provide you with choices regarding the Personal Information you provide to us. Below are some mechanisms that provide you with control over your information:</Text>
            <Text>Promotional Emails or other Electronic Communications. If you do not wish to receive promotional emails or other electronic communications from us, including but not limited to our e-newsletters, contact us at info@educationdirectory.org to opt-out or follow the unsubscribe process at the bottom of the promotional email or other electronic communication. Note that even if you opt-out, you may still receive transactional or account-related emails from us (e.g., emails related to the completion of your registration, correction of user data, password reset requests, reminder emails that you have requested, and any other similar communications essential to your transactions on or made through the Services).</Text>
            <Text>Telephone Calls and Texts. If you do not wish to receive promotional telephone calls from us, contact us at info@educationdirectory.org to opt-out, and we will add your phone number to our internal Do Not Call List. If you do not wish to receive texts, please follow the unsubscribe process in the text by typing “STOP” and sending it to us.</Text>
            <Text>Automatic Information Collection Technologies and Advertising. Our systems currently recognize "do not track" signals from your browser. In addition, the "help" function of your browser should contain instructions on how to set your browser to not accept new cookies, to notify you when a cookie is issued, or how to disable cookies altogether. If Flash cookies are used on the Services, you can manage your Flash cookie settings, by visiting the Flash player settings page on Adobe's website. If you disable or refuse cookies, please note that some parts of the Services may be inaccessible or not function properly.</Text>
            <Text>Disclosure of Your Information to Third-Parties for Advertising. If you no longer want us to share your Personal Information with non-affiliated third parties for promotional purposes, contact us at info@educationdirectory.org to opt-out. Any opt-out request will only apply from the date of your request, and we will not be responsible for any communications that you may receive from third parties who received your Personal Information prior to your request. In these cases, please contact the third parties directly.</Text>
            
            <Text fontWeight='bold' fontSize='lg'>Accessing and Correcting Your Information</Text>
            <Text>The appropriate method(s) for accessing your information, if any, will depend on which of our websites and services you have visited or used. Depending on the website and service, you may have the ability to view or edit some of your information online, by logging into the Services and visiting your account profile page. You may also contact us at info@educationdirectory.org to request access to, correct, or delete any Personal Information that you have provided to us;</Text>
            <Text>however, we may ask you to verify your identity and provide other details to help us to respond to your request. We will respond to your request within a reasonable timeframe.</Text>
            <Text>We cannot delete your Personal Information except by also deleting your user account, if applicable. Once your user account is deleted, it cannot be recovered. We also may not accommodate a request to change or delete information if we believe the change would violate any law or legal requirements, not allow us to enforce our agreements, be contrary to our Terms of Use or any other applicable agreement between you and us, or cause the information to be incorrect. After deletion of your user account, your Personal Information may remain on our archived database and records.</Text>
            <Text>To request removal of your personal information from our blog or forum, contact us at info@educationdirectory.org. In some cases, we may not be able to remove your Personal Information, in which case we will let you know if we are unable to do so and why. If you delete or request the deletion of your User Contributions from the Services, copies of your User Contributions may remain viewable in cached and archived pages, or might have been copied, stored, or reposted to another website by other users of the Services.</Text>
            <Text>Any updates you make or request to be made to your Personal Information will be applied in our own records but will not be updated in the records of the educational institutions or other third parties to which we have already shared your information. If you would like to make updates to the information that has been shared with educational institutions and other third parties, you will need to contact them separately.</Text>
            
            <Text fontWeight='bold' fontSize='lg'>Security</Text>
            <Text>We strive to use reasonable security measures to protect your information collected through the Services. However, no method of transmission or electronic storage is 100% effective, and we cannot guarantee absolute security. Therefore, your use of the Services is at your own risk and we do not promise or guarantee, and you should not expect, that your information will always and absolutely remain private and secure. We are not responsible for the circumvention of any privacy settings or security measures contained on or concerning the Services. You are also responsible for taking reasonable steps to protect your personal information against unauthorized disclosure or misuse.</Text>
            <Text>In the unlikely event that we believe that the security of your Personal Information in our possession or control may have been compromised, we may seek to notify you of that development. If a notification is appropriate, we would endeavor to do so as promptly as possible under the circumstances, and, if we have your email address, we may notify you by email. You consent to our use of email as a means of such notification. If you prefer for us to use another method to notify you in this situation, please email us at info@educationdirectory.org with the alternative contact information you wish to be used.</Text>
            
            <Text fontWeight='bold' fontSize='lg'>Minors</Text>
            <Text>Visitors under eighteen (18) years of age are not permitted to use and/or submit their personal information at the Site. Company does not knowingly solicit or collect information from visitors under eighteen (18) years of age.</Text>
            
            <Text fontWeight='bold' fontSize='lg'>Changes to This Privacy Policy</Text>
            <Text>We may update or amend this Privacy Policy at any time. This Privacy Policy will reflect the date it was last updated or amended. If we make any material amendments, we will notify you by posting a notice of the updated or amended Privacy Policy on the Services. All amendments will take effect immediately upon our posting of the updated Privacy Policy on the Services. Under certain circumstances, we may also elect to notify you of changes or updates to our Privacy Policy by additional means, such as posting a notice on the homepage of the Services or sending you an email. Please check this Privacy Policy each time you use the Services to ensure you are aware of any changes in our practices. Your continued use of the Services will indicate your acceptance of the changes to the Privacy Policy.</Text>
            
            <Text fontWeight='bold' fontSize='lg'>Notice to California Residents -- Your California Privacy Rights</Text>
            <Text>California's Shine the Light law provides California residents with the right to receive disclosures about any sharing of their personal information with other companies.</Text>
            <Text>If you are a California resident and you provided your personal information to Candid Maven, then, once each calendar year, you may submit a written request for information about the information we shared, if any, with other companies for their use in direct marketing. To submit your written request, please send a written request to:</Text>
            <Text>Education Directory<br/>3219 E Camelback Rd. Ste221<br/>Phoenix, AZ 85018</Text>
            <Text>You must include sufficient detail for us to locate your file; at a minimum, your name and postal address.</Text>
            <Text>Within 30 days of receiving your request, we will send you a list of the categories of personal information disclosed to third parties for third-party direct marketing purposes during the immediately preceding calendar year, along with the names and addresses of these third parties.</Text>
            <Text>We reserve our right not to respond to requests sent more than once in a calendar year, or requests submitted to an address other than the one posted in this notice. Please note that the California Shine the Light law does not cover all information sharing. Our disclosure only includes information covered by the law.</Text>
            
            <Text fontWeight='bold' fontSize='lg'>Privacy Policy – California</Text>
            <Text>This PRIVACY POLICY FOR CALIFORNIA RESIDENTS supplements the information contained in the Privacy Policy of Candid Maven (collectively, “we,” “us,” or “our”) and applies solely to visitors, users, and others who reside in the State of California (“consumers” or “you”). Any terms defined in the California Consumer Privacy Act (“CCPA”) have the same meaning when used in this notice.</Text>
            
            <Text fontWeight='bold' fontSize='lg'>Information We Collect</Text>
            <Text>We have collected the following categories of personal information from consumers within the last twelve (12) months:</Text>
            <Text>Table</Text>
            <Text>We obtain the categories of personal information listed above from the following categories of sources:</Text>
            <Text>Directly from consumers. For example, from information that consumers provide to us related to the services we provide.</Text>
            <Text>Directly and indirectly from schools, our marketing partners, affiliates, and service providers. For example, through information we collect from our partners in the course of providing or receiving services.</Text>
            <Text>Directly and indirectly from activity on our website(s). For example, from submissions through our website portal or website usage details collected automatically.</Text>
            
            <Text fontWeight='bold' fontSize='lg'>Use of Personal Information</Text>
            <Text>We use or disclose the personal information we collect for one or more of the following business purposes:</Text>
            <Text>To fulfill the purpose for which the information is provided. For example, if you share your personal information to request info on any schools or programs, we will use that personal information to respond to your inquiry.</Text>
            <Text>To provide you with emails, event registrations, and other notices concerning our products or services, or events or news, that may be of interest to you.</Text>
            <Text>To improve our website and present its contents to you.</Text>
            <Text>For testing, research, analysis and product development.</Text>
            <Text>As necessary or appropriate to protect the rights, property or safety of us, our clients or others, or to enforce our Terms of Use.</Text>
            <Text>To respond to law enforcement requests and as required by applicable law, court order, or governmental regulations.</Text>
            <Text>We will not collect additional categories of personal information or use the personal information we collected for additional purposes without providing you notice or obtaining your consent where required by law.</Text>
            
            <Text fontWeight='bold' fontSize='lg'>Sharing Personal Information</Text>
            <Text>We may sell your personal information to a third party or disclose your personal information for a business purpose. When we disclose personal information for a business purpose, we enter into a contract that describes the purpose and requires the recipient to both keep that personal information confidential and not use it for any purpose except performing the contract.</Text>
            <Text>In the preceding twelve (12) months, we have disclosed the following categories of personal information for a business purpose:</Text>
        
            <Text fontWeight='bold' fontSize='lg'>Do Not Sell My Personal Information</Text>
            <Text>You have the right to opt-out of the sale of your personal information; however, exercising this right does not affect any of your personal information that was sold prior to the filing of your opt-out request. To exercise your opt-out right, please request.</Text>
            
            <Text fontWeight='bold' fontSize='lg'>Privacy Policy - Nevada</Text>
            <Text>Residents of the State of Nevada have the right to opt out of the sale of certain pieces of their information to third parties who will sell or license their information to others. If you are a Nevada resident and would like to make such a request, please email info@educationdirectory.org or submit a request.</Text>
            
            <Text fontWeight='bold' fontSize='lg'>Contact Us</Text>
            <Text>If you have any questions about this Privacy Policy or our privacy practices in general, you may email us as at: info@educationdirectory.org; call us at: 800-719-5930; or send us mail to: info@educationdirectory.org; or send us mail to: Education Directory, 3219 E Camelback Rd. Ste221, Phoenix, AZ 85018.</Text>
            <Text>We may update this policy from time to time so please check our Privacy Policy section on the site periodically for changes.</Text>
        </Stack>
    );
};

export default PrivacyPolicy;